---
title: "Reproducible Research: Peer Assessment 1"
output: 
html_document:
keep_md: true
---


## Loading and preprocessing the data
```{r loadData, echo=FALSE}
library(ggplot2)
library(dplyr)

dt <- read.csv("activity.csv") 

##Remove zero activity data to compute mean/median.
dtNonZero <- filter(dt, steps != 0)  
```



## What is mean total number of steps taken per day?


```{r, echo=TRUE,fig.width=10}



dtByDate = aggregate(dt$steps, by=list(dt$date), FUN=sum, rm.na = T)    
colnames(dtByDate) <- c("Date", "Sum")  
dtByDate$Date <- strptime(dtByDate$Date, "%Y-%m-%d")  
dtByDate$Month <- months(dtByDate$Date)
dtByDate$Day <- as.numeric(format(dtByDate$Date , "%d"))
plotSum <- ggplot(dtByDate, aes(Day, weight= Sum)) + geom_bar(aes(fill = Month), position = "dodge", binwidth=.4) +
  scale_x_discrete(limit = c(1:31)) + xlab("Day of the month") + ylab("Sum (steps)") +
  ggtitle("Sum of the total steps across two months")


print (plotSum)


dtMedian = aggregate(dtNonZero$steps, by=list(dtNonZero$date), FUN=median)      
colnames(dtMedian) <- c("Date", "Median")
dtMedian$Date <- strptime(dtMedian$Date, "%Y-%m-%d")  
dtMedian$Month <- months(dtMedian$Date)
dtMedian$Day <- as.numeric(format(dtMedian$Date , "%d"))  
plotMedian <- ggplot(dtMedian, aes(Day, weight= Median)) + geom_bar(aes(fill = Month), position = "dodge", binwidth=.4) +
  scale_x_discrete(limit = c(1:31)) + xlab("Day of the month") + ylab("Median (steps)") +
  ggtitle("Median of the total steps across two months")

print (plotMedian)



dtMean = aggregate(dtNonZero$steps, by=list(dtNonZero$date), FUN=mean)      
colnames(dtMean) <- c("Date", "Mean")
dtMean$Date <- strptime(dtMean$Date, "%Y-%m-%d")  
dtMean$Month <- months(dtMean$Date)
dtMean$Day <- as.numeric(format(dtMean$Date , "%d"))  
plotMean <- ggplot(dtMean, aes(Day, weight= Mean)) + geom_bar(aes(fill = Month), position = "dodge", binwidth=.4) +
  scale_x_discrete(limit = c(1:31)) + xlab("Day of the month") + ylab("Mean (steps)") + 
  ggtitle("Mean of the total steps across two months")

print (plotMean)
```


## What is the average daily activity pattern?


```{r, echo=TRUE,fig.width=10, fig.height=7}
dtAvgIntervals <- filter(dt, steps != 0 & !is.na(steps))  
dtAvgIntervals <- aggregate(dtAvgIntervals$steps, by=list(dtAvgIntervals$interval), FUN=mean, rm.na = T)
colnames(dtAvgIntervals) <- c("Interval", "Average")  
with (dtAvgIntervals, plot(Interval, 
                           Average, 
                           type="l", 
                           xlab="Interval time series", 
                           ylab="Averages", 
                           main="Daily average by intervals"))

dtAvgIntervals <- dtAvgIntervals[order(dtAvgIntervals$Average),]

maxActivity <- dtAvgIntervals[nrow(dtAvgIntervals),]


```


5-minute interval, on average across all the days in the dataset, contains the maximum number of steps: 

```{r}
print(maxActivity, type="html",row.names =FALSE )

```


## Inputing missing values



## Are there differences in activity patterns between weekdays and weekends?
